//
//  Question.swift
//  QuizApp
//
//  Created by jaemin park on 2022/01/23.
//

import Foundation

struct Question: Hashable {
    let questionText: String
    let possibleAnswers: [String]
    let correctAnswerIndex: Int
    
    static let allQuestions: [Question] = [
    Question(questionText: "How do you read this word?雨",
             possibleAnswers: [
             "ゆき",
             "はれ",
             "くもり",
             "あめ",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "How do you read this word?書いて",
             possibleAnswers: [
             "かいて",
             "きいて",
             "はいて",
             "ひいて",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "How do you read this word?中",
             possibleAnswers: [
             "そば",
             "そと",
             "なか",
             "よこ",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "How do you read this word?小さい",
             possibleAnswers: [
             "ちいさい",
             "ちさい",
             "しいさい",
             "しさい",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "How do you read this word?火よう日",
             possibleAnswers: [
             "どようび",
             "すいようび",
             "かようび",
             "にちようび",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "How do you read this word?空",
             possibleAnswers: [
             "いえ",
             "うみ",
             "にわ",
             "そら",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "How do you read this word?百人",
             possibleAnswers: [
             "ひゃくにん",
             "びゃくにん",
             "ひゃくじん",
             "びゃくじん",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "How do you read this word?魚",
             possibleAnswers: [
             "ねこ",
             "とり",
             "いぬ",
             "さかな",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "How do you read this word?半分",
             possibleAnswers: [
             "はんふん",
             "はんぶん",
             "ほんぶん",
             "ほんふん",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "How do you read this word?間",
             possibleAnswers: [
             "あいた",
             "となり",
             "あいだ",
             "どなり",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "How do you read this word?三つ",
             possibleAnswers: [
             "いつつ",
             "みっつ",
             "さんつ",
             "ごつ",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "How do you read this word?元気",
             possibleAnswers: [
             "けんき",
             "げんき",
             "でんき",
             "てんき",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "How do you write this word?わいしゃつ",
             possibleAnswers: [
             "ウイシャソ",
             "ウイシャツ",
             "ワイシャソ",
             "ワイシャツ",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "How do you write this word?かわ",
             possibleAnswers: [
             "花",
             "山",
             "川",
             "木",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "How do you write this word?がっこう",
             possibleAnswers: [
             "宇校",
             "学校",
             "宇枚",
             "学枚",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "How do you write this word?みて",
             possibleAnswers: [
             "見て",
             "買て",
             "貝て",
             "目て",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "How do you write this word?たかい",
             possibleAnswers: [
             "高い",
             "安い",
             "古い",
             "新い",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "How do you write this word?かいしゃ",
             possibleAnswers: [
             "公仕",
             "公社",
             "会仕",
             "会社",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "How do you write this word?いわないで",
             possibleAnswers: [
             "行わないで",
             "立わないで",
             "言わないで",
             "食わないで",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "How do you write this word?らいげつ",
             possibleAnswers: [
             "今月",
             "来月",
             "来週",
             "今週",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "What's the right word in parentheses?わたしの へやは この アパートの 2( )です.",
             possibleAnswers: [
             "ほん",
             "さつ",
             "だい",
             "かい",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "What's the right word in parentheses?その ナイフで りんごを( )ください。",
             possibleAnswers: [
             "おきて",
             "つけて",
             "しめて",
             "きって",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "What's the right word in parentheses?( )を わすれましたから、じかんが わかりません。",
             possibleAnswers: [
             "じしょ",
             "ちず",
             "とけい",
             "さいふ",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "What's the right word in parentheses?わたしの うちは えきに ちかいですから、( )です。",
             possibleAnswers: [
             "べんり",
             "じょうぶ",
             "いっぱい",
             "へた",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "What's the right word in parentheses?なつやすみは まいにち( )で およぎました。",
             possibleAnswers: [
             "レストラン",
             "プール",
             "エレベーター",
             "ビル",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "What's the right word in parentheses?しらない ことばが ありましたから、せんせいに( )しました。",
             possibleAnswers: [
             "しつもん",
             "べんきょう",
             "れんしゅう",
             "じゅぎょう",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "What's the right word in parentheses?この へやは あついですから、( )を あけましょう。",
             possibleAnswers: [
             "おふろ",
             "まど",
             "エアコン",
             "テーブル",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "What's the right word in parentheses?きのうは がっこうで たくさん かんじを(  )",
             possibleAnswers: [
             "うりました",
             "もちました",
             "おぼえました",
             "こまりました",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "What's the right word in parentheses?この コーヒーは、さとうを たくさん いれましたから、 (  )です。",
             possibleAnswers: [
             "わかい",
             "くろい",
             "まるい",
             "あまい",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "What's the right word in parentheses?つよい かぜが ( ) います。",
             possibleAnswers: [
             "ふいて",
             "いそいで",
             "とんで",
             "はしって",
             ],
             correctAnswerIndex: 0),
    ]
}
